# Please note that the generation of uniform_types depends on having
# the GL object already created and exported by {glfw}. This is bad practice,
# I know, I hope to fix this in the future.

library(tidyverse)
library(glfw)

uniform_types <- tribble(
  ~ constant, ~ type,
  GL$FLOAT, "float",
  GL$FLOAT_VEC2, "vec2",
  GL$FLOAT_VEC3, "vec3",
  GL$FLOAT_VEC4, "vec4",
  GL$DOUBLE, "double",
  GL$DOUBLE_VEC2, "dvec2",
  GL$DOUBLE_VEC3, "dvec3",
  GL$DOUBLE_VEC4, "dvec4",
  GL$INT, "int",
  GL$INT_VEC2, "ivec2",
  GL$INT_VEC3, "ivec3",
  GL$INT_VEC4, "ivec4",
  GL$UNSIGNED_INT, "unsigned int",
  GL$UNSIGNED_INT_VEC2, "uvec2",
  GL$UNSIGNED_INT_VEC3, "uvec3",
  GL$UNSIGNED_INT_VEC4, "uvec4",
  GL$BOOL, "bool",
  GL$BOOL_VEC2, "bvec2",
  GL$BOOL_VEC3, "bvec3",
  GL$BOOL_VEC4, "bvec4",
  GL$FLOAT_MAT2, "mat2",
  GL$FLOAT_MAT3, "mat3",
  GL$FLOAT_MAT4, "mat4",
  GL$FLOAT_MAT2x3, "mat2x3",
  GL$FLOAT_MAT2x4, "mat2x4",
  GL$FLOAT_MAT3x2, "mat3x2",
  GL$FLOAT_MAT3x4, "mat3x4",
  GL$FLOAT_MAT4x2, "mat4x2",
  GL$FLOAT_MAT4x3, "mat4x3",
  GL$DOUBLE_MAT2, "dmat2",
  GL$DOUBLE_MAT3, "dmat3",
  GL$DOUBLE_MAT4, "dmat4",
  GL$DOUBLE_MAT2x3, "dmat2x3",
  GL$DOUBLE_MAT2x4, "dmat2x4",
  GL$DOUBLE_MAT3x2, "dmat3x2",
  GL$DOUBLE_MAT3x4, "dmat3x4",
  GL$DOUBLE_MAT4x2, "dmat4x2",
  GL$DOUBLE_MAT4x3, "dmat4x3",
  GL$SAMPLER_1D, "sampler1D",
  GL$SAMPLER_2D, "sampler2D",
  GL$SAMPLER_3D, "sampler3D",
  GL$SAMPLER_CUBE, "samplerCube",
  GL$SAMPLER_1D_SHADOW, "sampler1DShadow",
  GL$SAMPLER_2D_SHADOW, "sampler2DShadow",
  GL$SAMPLER_1D_ARRAY, "sampler1DArray",
  GL$SAMPLER_2D_ARRAY, "sampler2DArray",
  GL$SAMPLER_1D_ARRAY_SHADOW, "sampler1DArrayShadow",
  GL$SAMPLER_2D_ARRAY_SHADOW, "sampler2DArrayShadow",
  GL$SAMPLER_2D_MULTISAMPLE, "sampler2DMS",
  GL$SAMPLER_2D_MULTISAMPLE_ARRAY, "sampler2DMSArray",
  GL$SAMPLER_CUBE_SHADOW, "samplerCubeShadow",
  GL$SAMPLER_BUFFER, "samplerBuffer",
  GL$SAMPLER_2D_RECT, "sampler2DRect",
  GL$SAMPLER_2D_RECT_SHADOW, "sampler2DRectShadow",
  GL$INT_SAMPLER_1D, "isampler1D",
  GL$INT_SAMPLER_2D, "isampler2D",
  GL$INT_SAMPLER_3D, "isampler3D",
  GL$INT_SAMPLER_CUBE, "isamplerCube",
  GL$INT_SAMPLER_1D_ARRAY, "isampler1DArray",
  GL$INT_SAMPLER_2D_ARRAY, "isampler2DArray",
  GL$INT_SAMPLER_2D_MULTISAMPLE, "isampler2DMS",
  GL$INT_SAMPLER_2D_MULTISAMPLE_ARRAY, "isampler2DMSArray",
  GL$INT_SAMPLER_BUFFER, "isamplerBuffer",
  GL$INT_SAMPLER_2D_RECT, "isampler2DRect",
  GL$UNSIGNED_INT_SAMPLER_1D, "usampler1D",
  GL$UNSIGNED_INT_SAMPLER_2D, "usampler2D",
  GL$UNSIGNED_INT_SAMPLER_3D, "usampler3D",
  GL$UNSIGNED_INT_SAMPLER_CUBE, "usamplerCube",
  GL$UNSIGNED_INT_SAMPLER_1D_ARRAY, "usampler2DArray",
  GL$UNSIGNED_INT_SAMPLER_2D_ARRAY, "usampler2DArray",
  GL$UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE, "usampler2DMS",
  GL$UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, "usampler2DMSArray",
  GL$UNSIGNED_INT_SAMPLER_BUFFER, "usamplerBuffer",
  GL$UNSIGNED_INT_SAMPLER_2D_RECT, "usampler2DRect",
  GL$IMAGE_1D, "image1D",
  GL$IMAGE_2D, "image2D",
  GL$IMAGE_3D, "image3D",
  GL$IMAGE_2D_RECT, "image2DRect",
  GL$IMAGE_CUBE, "imageCube",
  GL$IMAGE_BUFFER, "imageBuffer",
  GL$IMAGE_1D_ARRAY, "image1DArray",
  GL$IMAGE_2D_ARRAY, "image2DArray",
  GL$IMAGE_2D_MULTISAMPLE, "image2DMS",
  GL$IMAGE_2D_MULTISAMPLE_ARRAY, "image2DMSArray",
  GL$INT_IMAGE_1D, "iimage1D",
  GL$INT_IMAGE_2D, "iimage2D",
  GL$INT_IMAGE_3D, "iimage3D",
  GL$INT_IMAGE_2D_RECT, "iimage2DRect",
  GL$INT_IMAGE_CUBE, "iimageCube",
  GL$INT_IMAGE_BUFFER, "iimageBuffer",
  GL$INT_IMAGE_1D_ARRAY, "iimage1DArray",
  GL$INT_IMAGE_2D_ARRAY, "iimage2DArray",
  GL$INT_IMAGE_2D_MULTISAMPLE, "iimage2DMS",
  GL$INT_IMAGE_2D_MULTISAMPLE_ARRAY, "iimage2DMSArray",
  GL$UNSIGNED_INT_IMAGE_1D, "uimage1D",
  GL$UNSIGNED_INT_IMAGE_2D, "uimage2D",
  GL$UNSIGNED_INT_IMAGE_3D, "uimage3D",
  GL$UNSIGNED_INT_IMAGE_2D_RECT, "uimage2DRect",
  GL$UNSIGNED_INT_IMAGE_CUBE, "uimageCube",
  GL$UNSIGNED_INT_IMAGE_BUFFER, "uimageBuffer",
  GL$UNSIGNED_INT_IMAGE_1D_ARRAY, "uimage1DArray",
  GL$UNSIGNED_INT_IMAGE_2D_ARRAY, "uimage2DArray",
  GL$UNSIGNED_INT_IMAGE_2D_MULTISAMPLE, "uimage2DMS",
  GL$UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY, "uimage2DMSArray",
  GL$UNSIGNED_INT_ATOMIC_COUNTER, "atomic_uint",
)

usethis::use_data(uniform_types, overwrite = TRUE)
