#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP glad_load_gl_();
extern SEXP glfw_create_window_(SEXP, SEXP, SEXP);
extern SEXP glfw_destroy_window_(SEXP);
extern SEXP glfw_get_error_();
extern SEXP glfw_get_version_();
extern SEXP glfw_get_version_string_();
extern SEXP glfw_get_window_size_(SEXP);
extern SEXP glfw_init_();
extern SEXP glfw_make_context_current_(SEXP);
extern SEXP glfw_set_error_callback_(SEXP);
extern SEXP glfw_terminate_();
extern SEXP glfw_window_hint_(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"glad_load_gl_",              (DL_FUNC) &glad_load_gl_,              0},
    {"glfw_create_window_",        (DL_FUNC) &glfw_create_window_,        3},
    {"glfw_destroy_window_",       (DL_FUNC) &glfw_destroy_window_,       1},
    {"glfw_get_error_",            (DL_FUNC) &glfw_get_error_,            0},
    {"glfw_get_version_",          (DL_FUNC) &glfw_get_version_,          0},
    {"glfw_get_version_string_",   (DL_FUNC) &glfw_get_version_string_,   0},
    {"glfw_get_window_size_",      (DL_FUNC) &glfw_get_window_size_,      1},
    {"glfw_init_",                 (DL_FUNC) &glfw_init_,                 0},
    {"glfw_make_context_current_", (DL_FUNC) &glfw_make_context_current_, 1},
    {"glfw_set_error_callback_",   (DL_FUNC) &glfw_set_error_callback_,   1},
    {"glfw_terminate_",            (DL_FUNC) &glfw_terminate_,            0},
    {"glfw_window_hint_",          (DL_FUNC) &glfw_window_hint_,          2},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_glfw(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
